#-------------------------------------------
# InvoiceShelf PostgreSQL docker-compose variant
# Repo : https://github.com/InvoiceShelf/docker
#-------------------------------------------

services:
  invoiceshelf_db:
    container_name: invoiceshelf_db
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=6e5WEMY6e5WEMY
      - POSTGRES_USER=invoiceshelf
      - POSTGRES_DB=invoiceshelf
    networks:
      - invoiceshelf
    restart: unless-stopped

  invoiceshelf:
    image: invoiceshelf/invoiceshelf:nightly
    container_name: invoiceshelf
    ports:
      - 80:80
    volumes:
      - ./invoiceshelf_pgsql/data:/data
      - ./invoiceshelf_pgsql/conf:/conf
      - ./invoiceshelf_pgsql/sessions:/var/www/html/storage/framework/sessions
    networks:
      - invoiceshelf
    environment:
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - DB_CONNECTION=pgsql
      - DB_HOST=invoiceshelf_db
      - DB_PORT=5432
      - DB_DATABASE=invoiceshelf
      - DB_USERNAME=invoiceshelf
      - DB_PASSWORD=6e5WEMY6e5WEMY
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - SESSION_LIFETIME=7200
      - SESSION_ENCRYPT=false
      - SESSION_PATH=/
      - SESSION_DOMAIN=
      - SANCTUM_STATEFUL_DOMAINS=localhost
      - STARTUP_DELAY=10
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USERNAME=u2100960@siswa.um.edu.my
      - MAIL_PASSWORD=qubaaigdzhoavzoa
      # - MAIL_PASSWORD_FILE=<filename>
      - MAIL_ENCRYPTION=tls
    restart: unless-stopped
    depends_on:
      - invoiceshelf_db

networks:
  invoiceshelf: